apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: ${namespace}
  labels:
    app: postgres
data:
  POSTGRES_DB: ${postgres_db}
  POSTGRES_USER: ${postgres_user}
  POSTGRES_PASSWORD: ${postgres_password}