apiVersion: v1
kind: Service
metadata:
  name: historical-hs
  namespace: ${namespace}
  labels:
    app: historical
spec:
  ports:
  - port: 8083
    name: historical
  clusterIP: None
  selector:
    app: historical
---
apiVersion: v1
kind: Service
metadata:
  name: historical-cs
  namespace: ${namespace}
  labels:
    app: historical
spec:
  ports:
  - port: 8083
    name: historical
  selector:
    app: historical