apiVersion: v1
kind: Service
metadata:
  name: router-hs
  namespace: ${namespace}
  labels:
    app: router
spec:
  ports:
  - port: 8888
    name: router
  clusterIP: None
  selector:
    app: router
---
apiVersion: v1
kind: Service
metadata:
  name: router-cs
  namespace: ${namespace}
  labels:
    app: router
spec:
  ports:
  - port: 8888
    name: router
  selector:
    app: router