apiVersion: v1
kind: Secret
metadata:
  name: druid-secret
  namespace: ${namespace}
type: Opaque
data:
  aws_access_key: ${aws_access_key}
  aws_secret_key: ${aws_secret_key}
  aws_region: ${aws_region}
  aws_bucket_storage: ${aws_bucket_storage}
  aws_bucket_index: ${aws_bucket_index}